// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tenkclvpxbmqxivtkgyr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRlbmtjbHZweGJtcXhpdnRrZ3lyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0OTIxMzUsImV4cCI6MjA2OTA2ODEzNX0.-0GB1AXlBCB8VuDff5WbH2X9powzPGEBbLB-ieWjUX4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});